services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\SwissQrBundle\:
        resource: '../../*'
        exclude: '../../{Resources,vendor}'

    KimaiPlugin\SwissQrBundle\EventSubscriber\InvoiceSubscriber:
        tags:
            - { name: kernel.event_subscriber }